//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1.TestSuite {
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Reflection;
    using Microsoft.SpecExplorer.Runtime.Testing;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Spec Explorer", "3.5.3130.0")]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class ReceiveWithCheckersTestSuite : VsTestClassBase {
        
        public ReceiveWithCheckersTestSuite() {
            this.SetSwitch("ProceedControlTimeout", "100");
            this.SetSwitch("QuiescenceTimeout", "30000");
        }
        
        #region Test Initialization and Cleanup
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize() {
            this.InitializeTestManager();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void TestCleanup() {
            this.CleanupTestManager();
        }
        #endregion
        
        #region Test Starting in S0
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void ReceiveWithCheckersTestSuiteS0() {
            this.Manager.BeginTest("ReceiveWithCheckersTestSuiteS0");
            this.Manager.Comment("reaching state \'S0\'");
            this.Manager.Comment("executing step \'call Checker(0)\'");
            Project1.TestAdapter.AdapterClass.Checker(0);
            this.Manager.Comment("reaching state \'S1\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S4\'");
            this.Manager.Comment("executing step \'call AdapterSendReadRequest()\'");
            Project1.TestAdapter.AdapterClass.AdapterSendReadRequest();
            this.Manager.Comment("reaching state \'S6\'");
            this.Manager.Comment("checking step \'return AdapterSendReadRequest\'");
            this.Manager.Comment("reaching state \'S8\'");
            this.Manager.Comment("executing step \'call Checker(3)\'");
            Project1.TestAdapter.AdapterClass.Checker(3);
            this.Manager.Comment("reaching state \'S10\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S12\'");
            this.Manager.Comment("executing step \'call AdapterReceiveDataBlock()\'");
            Project1.TestAdapter.AdapterClass.AdapterReceiveDataBlock();
            this.Manager.Comment("reaching state \'S14\'");
            this.Manager.Comment("checking step \'return AdapterReceiveDataBlock\'");
            this.Manager.Comment("reaching state \'S16\'");
            this.Manager.Comment("executing step \'call Checker(4)\'");
            Project1.TestAdapter.AdapterClass.Checker(4);
            this.Manager.Comment("reaching state \'S18\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S20\'");
            this.Manager.Comment("executing step \'call AdapterSendACK()\'");
            Project1.TestAdapter.AdapterClass.AdapterSendACK();
            this.Manager.Comment("reaching state \'S22\'");
            this.Manager.Comment("checking step \'return AdapterSendACK\'");
            this.Manager.Comment("reaching state \'S24\'");
            this.Manager.Comment("executing step \'call Checker(5)\'");
            Project1.TestAdapter.AdapterClass.Checker(5);
            this.Manager.Comment("reaching state \'S26\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S28\'");
            this.Manager.Comment("executing step \'call AdapterReceiveDataBlock()\'");
            Project1.TestAdapter.AdapterClass.AdapterReceiveDataBlock();
            this.Manager.Comment("reaching state \'S30\'");
            this.Manager.Comment("checking step \'return AdapterReceiveDataBlock\'");
            this.Manager.Comment("reaching state \'S32\'");
            this.Manager.Comment("executing step \'call Checker(4)\'");
            Project1.TestAdapter.AdapterClass.Checker(4);
            this.Manager.Comment("reaching state \'S34\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S36\'");
            bool temp0;
            this.Manager.Comment("executing step \'call AdapterCanGetExit(510)\'");
            temp0 = Project1.TestAdapter.AdapterClass.AdapterCanGetExit(510);
            this.Manager.Comment("reaching state \'S38\'");
            this.Manager.Comment("checking step \'return AdapterCanGetExit/True\'");
            TestManagerHelpers.AssertAreEqual<bool>(this.Manager, true, temp0, "return of AdapterCanGetExit, state S38");
            this.Manager.Comment("reaching state \'S40\'");
            this.Manager.Comment("executing step \'call Checker(1)\'");
            Project1.TestAdapter.AdapterClass.Checker(1);
            this.Manager.Comment("reaching state \'S42\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S44\'");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S2
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void ReceiveWithCheckersTestSuiteS2() {
            this.Manager.BeginTest("ReceiveWithCheckersTestSuiteS2");
            this.Manager.Comment("reaching state \'S2\'");
            this.Manager.Comment("executing step \'call Checker(0)\'");
            Project1.TestAdapter.AdapterClass.Checker(0);
            this.Manager.Comment("reaching state \'S3\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S5\'");
            this.Manager.Comment("executing step \'call AdapterSendReadRequest()\'");
            Project1.TestAdapter.AdapterClass.AdapterSendReadRequest();
            this.Manager.Comment("reaching state \'S7\'");
            this.Manager.Comment("checking step \'return AdapterSendReadRequest\'");
            this.Manager.Comment("reaching state \'S9\'");
            this.Manager.Comment("executing step \'call Checker(3)\'");
            Project1.TestAdapter.AdapterClass.Checker(3);
            this.Manager.Comment("reaching state \'S11\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S13\'");
            this.Manager.Comment("executing step \'call AdapterReceiveDataBlock()\'");
            Project1.TestAdapter.AdapterClass.AdapterReceiveDataBlock();
            this.Manager.Comment("reaching state \'S15\'");
            this.Manager.Comment("checking step \'return AdapterReceiveDataBlock\'");
            this.Manager.Comment("reaching state \'S17\'");
            this.Manager.Comment("executing step \'call Checker(4)\'");
            Project1.TestAdapter.AdapterClass.Checker(4);
            this.Manager.Comment("reaching state \'S19\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S21\'");
            this.Manager.Comment("executing step \'call AdapterSendACK()\'");
            Project1.TestAdapter.AdapterClass.AdapterSendACK();
            this.Manager.Comment("reaching state \'S23\'");
            this.Manager.Comment("checking step \'return AdapterSendACK\'");
            this.Manager.Comment("reaching state \'S25\'");
            this.Manager.Comment("executing step \'call Checker(5)\'");
            Project1.TestAdapter.AdapterClass.Checker(5);
            this.Manager.Comment("reaching state \'S27\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S29\'");
            this.Manager.Comment("executing step \'call AdapterReceiveDataBlock()\'");
            Project1.TestAdapter.AdapterClass.AdapterReceiveDataBlock();
            this.Manager.Comment("reaching state \'S31\'");
            this.Manager.Comment("checking step \'return AdapterReceiveDataBlock\'");
            this.Manager.Comment("reaching state \'S33\'");
            this.Manager.Comment("executing step \'call Checker(4)\'");
            Project1.TestAdapter.AdapterClass.Checker(4);
            this.Manager.Comment("reaching state \'S35\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S37\'");
            bool temp1;
            this.Manager.Comment("executing step \'call AdapterCanGetExit(520)\'");
            temp1 = Project1.TestAdapter.AdapterClass.AdapterCanGetExit(520);
            this.Manager.Comment("reaching state \'S39\'");
            this.Manager.Comment("checking step \'return AdapterCanGetExit/False\'");
            TestManagerHelpers.AssertAreEqual<bool>(this.Manager, false, temp1, "return of AdapterCanGetExit, state S39");
            this.Manager.Comment("reaching state \'S41\'");
            this.Manager.Comment("executing step \'call Checker(4)\'");
            Project1.TestAdapter.AdapterClass.Checker(4);
            this.Manager.Comment("reaching state \'S43\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S45\'");
            this.Manager.Comment("executing step \'call AdapterSendACK()\'");
            Project1.TestAdapter.AdapterClass.AdapterSendACK();
            this.Manager.Comment("reaching state \'S46\'");
            this.Manager.Comment("checking step \'return AdapterSendACK\'");
            this.Manager.Comment("reaching state \'S47\'");
            this.Manager.Comment("executing step \'call Checker(5)\'");
            Project1.TestAdapter.AdapterClass.Checker(5);
            this.Manager.Comment("reaching state \'S48\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S49\'");
            this.Manager.Comment("executing step \'call AdapterReceiveDataBlock()\'");
            Project1.TestAdapter.AdapterClass.AdapterReceiveDataBlock();
            this.Manager.Comment("reaching state \'S50\'");
            this.Manager.Comment("checking step \'return AdapterReceiveDataBlock\'");
            this.Manager.Comment("reaching state \'S51\'");
            this.Manager.Comment("executing step \'call Checker(4)\'");
            Project1.TestAdapter.AdapterClass.Checker(4);
            this.Manager.Comment("reaching state \'S52\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S53\'");
            bool temp2;
            this.Manager.Comment("executing step \'call AdapterCanGetExit(510)\'");
            temp2 = Project1.TestAdapter.AdapterClass.AdapterCanGetExit(510);
            this.Manager.Comment("reaching state \'S54\'");
            this.Manager.Comment("checking step \'return AdapterCanGetExit/True\'");
            TestManagerHelpers.AssertAreEqual<bool>(this.Manager, true, temp2, "return of AdapterCanGetExit, state S54");
            this.Manager.Comment("reaching state \'S55\'");
            this.Manager.Comment("executing step \'call Checker(1)\'");
            Project1.TestAdapter.AdapterClass.Checker(1);
            this.Manager.Comment("reaching state \'S56\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S57\'");
            this.Manager.EndTest();
        }
        #endregion
    }
}
