//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1.TestSuite {
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Reflection;
    using Microsoft.SpecExplorer.Runtime.Testing;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Spec Explorer", "3.5.3130.0")]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class ReceiveTestSuite : VsTestClassBase {
        
        public ReceiveTestSuite() {
            this.SetSwitch("ProceedControlTimeout", "100");
            this.SetSwitch("QuiescenceTimeout", "30000");
        }
        
        #region Test Initialization and Cleanup
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize() {
            this.InitializeTestManager();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void TestCleanup() {
            this.CleanupTestManager();
        }
        #endregion
        
        #region Test Starting in S0
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void ReceiveTestSuiteS0() {
            this.Manager.BeginTest("ReceiveTestSuiteS0");
            this.Manager.Comment("reaching state \'S0\'");
            this.Manager.Comment("executing step \'call AdapterSendReadRequest()\'");
            Project1.TestAdapter.AdapterClass.AdapterSendReadRequest();
            this.Manager.Comment("reaching state \'S1\'");
            this.Manager.Comment("checking step \'return AdapterSendReadRequest\'");
            this.Manager.Comment("reaching state \'S2\'");
            this.Manager.Comment("executing step \'call AdapterReceiveDataBlock()\'");
            Project1.TestAdapter.AdapterClass.AdapterReceiveDataBlock();
            this.Manager.Comment("reaching state \'S3\'");
            this.Manager.Comment("checking step \'return AdapterReceiveDataBlock\'");
            this.Manager.Comment("reaching state \'S4\'");
            this.Manager.Assert(false, "reached non-accepting end state \'S4\'.");
            this.Manager.EndTest();
        }
        #endregion
    }
}
